on:
  workflow_call:
jobs:
  brakeman:
    name: rails
    uses: ./.github/workflows/brakeman.yml
  docker:
    name: rails
    uses: ./.github/workflows/docker.yml
  haml-lint:
    name: rails
    uses: ./.github/workflows/haml-lint.yml
  oxfmt:
    name: rails
    uses: ./.github/workflows/oxfmt.yml
  oxlint:
    name: rails
    uses: ./.github/workflows/oxlint.yml
  rspec:
    name: rails
    uses: ./.github/workflows/rspec-rails.yml
  rubocop:
    name: rails
    uses: ./.github/workflows/rubocop.yml
  stylelint:
    name: rails
    uses: ./.github/workflows/stylelint.yml
