on:
  workflow_call:
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.6@sha256:23616f0bd3aff922f4dea4130f1d0a09f3571d20b7b36c8f49840672dc309e8c
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
        ports:
          - 3306:3306
    env:
      RAILS_ENV: test
      DATABASE_URL: trilogy://root@127.0.0.1:3306/rails_test
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: bin/rails db:create db:schema:load test:prepare
      - run: bundle exec rspec
